### ISSUE TITLE
Is there a plan to release it as a dotnet tool?

### ISSUE THREAD

**Issue by xbotter** [lemillermicrosoft/skonsole#1]
This is a great tool. If there are any plans to release it as a dotnet tool in the future for easier installation and use?

**Comment by lemillermicrosoft** [comment]
I'd love to do this, been on my personal backlog. Back from vacation now! Thanks for filing the issue for visibilty/tracking.

**Comment by lemillermicrosoft** [comment]
Done! `dotnet tool install --global SKonsole --version 1.0.0` . Will need to do some more work, but high level, this is available now! Please give feedback and/or open new issues.
